// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM4lwCAmQlt9zgIeUWC1pXLDgwEhvRHYM',
    appId: '1:433686662880:web:47defb4a9a7ff7d60eca85',
    messagingSenderId: '433686662880',
    projectId: 'chat-app-44289',
    authDomain: 'chat-app-44289.firebaseapp.com',
    storageBucket: 'chat-app-44289.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF44FZZPawQL_ALjxFDA4uz6PH8cjHcXo',
    appId: '1:433686662880:android:a0af5a61973b74fd0eca85',
    messagingSenderId: '433686662880',
    projectId: 'chat-app-44289',
    storageBucket: 'chat-app-44289.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHv5z9i42IO6UvpZU8OAq995VpZN32u5Y',
    appId: '1:433686662880:ios:caf0118dfaa392e00eca85',
    messagingSenderId: '433686662880',
    projectId: 'chat-app-44289',
    storageBucket: 'chat-app-44289.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHv5z9i42IO6UvpZU8OAq995VpZN32u5Y',
    appId: '1:433686662880:ios:caf0118dfaa392e00eca85',
    messagingSenderId: '433686662880',
    projectId: 'chat-app-44289',
    storageBucket: 'chat-app-44289.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM4lwCAmQlt9zgIeUWC1pXLDgwEhvRHYM',
    appId: '1:433686662880:web:e4e8fa86517e945c0eca85',
    messagingSenderId: '433686662880',
    projectId: 'chat-app-44289',
    authDomain: 'chat-app-44289.firebaseapp.com',
    storageBucket: 'chat-app-44289.appspot.com',
  );
}
