// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFT9JrF6YPiebphIgj9EA8icE8yF7r_78',
    appId: '1:325620576748:web:6cd8d20fa615b0bdfc10c9',
    messagingSenderId: '325620576748',
    projectId: 'chat-6880d',
    authDomain: 'chat-6880d.firebaseapp.com',
    storageBucket: 'chat-6880d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOqMeB_vMIxpb1Eowzr0QxdwpaFvm5V0U',
    appId: '1:325620576748:android:ec2bea3da7590301fc10c9',
    messagingSenderId: '325620576748',
    projectId: 'chat-6880d',
    storageBucket: 'chat-6880d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKaeHhjBWAdlT177zSVAWMZJxTQG6clts',
    appId: '1:325620576748:ios:7d38831f66c9ba3ffc10c9',
    messagingSenderId: '325620576748',
    projectId: 'chat-6880d',
    storageBucket: 'chat-6880d.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKaeHhjBWAdlT177zSVAWMZJxTQG6clts',
    appId: '1:325620576748:ios:7d38831f66c9ba3ffc10c9',
    messagingSenderId: '325620576748',
    projectId: 'chat-6880d',
    storageBucket: 'chat-6880d.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFT9JrF6YPiebphIgj9EA8icE8yF7r_78',
    appId: '1:325620576748:web:43be00966b928641fc10c9',
    messagingSenderId: '325620576748',
    projectId: 'chat-6880d',
    authDomain: 'chat-6880d.firebaseapp.com',
    storageBucket: 'chat-6880d.appspot.com',
  );
}
