// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOj-6bQatNJwg2dZqy8NcEiePOngqaiKw',
    appId: '1:558377462258:web:dd751d2c105f912cc1e36b',
    messagingSenderId: '558377462258',
    projectId: 'chatbot-b45b6',
    authDomain: 'chatbot-b45b6.firebaseapp.com',
    storageBucket: 'chatbot-b45b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAszJ5YWm3TYfWbEJXgJrh2kAtnr4KCZo8',
    appId: '1:558377462258:android:3c8676ee4b5b33a0c1e36b',
    messagingSenderId: '558377462258',
    projectId: 'chatbot-b45b6',
    storageBucket: 'chatbot-b45b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8lPr_vRIz2p-N7yOnDtej2tnfvXLitbY',
    appId: '1:558377462258:ios:31b1554cbdf64983c1e36b',
    messagingSenderId: '558377462258',
    projectId: 'chatbot-b45b6',
    storageBucket: 'chatbot-b45b6.appspot.com',
    iosClientId: '558377462258-na0avj288v8548uc8jls81uif2hnbv73.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8lPr_vRIz2p-N7yOnDtej2tnfvXLitbY',
    appId: '1:558377462258:ios:31b1554cbdf64983c1e36b',
    messagingSenderId: '558377462258',
    projectId: 'chatbot-b45b6',
    storageBucket: 'chatbot-b45b6.appspot.com',
    iosClientId: '558377462258-na0avj288v8548uc8jls81uif2hnbv73.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOj-6bQatNJwg2dZqy8NcEiePOngqaiKw',
    appId: '1:558377462258:web:28669a3eca90eb25c1e36b',
    messagingSenderId: '558377462258',
    projectId: 'chatbot-b45b6',
    authDomain: 'chatbot-b45b6.firebaseapp.com',
    storageBucket: 'chatbot-b45b6.appspot.com',
  );
}
