name: s_potify
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg:
  flutter_bloc:
  hydrated_bloc:
  path_provider:
      

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/vectors/
    - assets/fonts/
  
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Variable.ttf 
        - asset: assets/fonts/Satoshi-VariableItalic.ttf 
