// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASW-cm1sodJjoiHfmSEuWbMmmiu2D63hE',
    appId: '1:615484235727:web:6c8c3d924caa31c6b2bcba',
    messagingSenderId: '615484235727',
    projectId: 'learn-auth-ff6fe',
    authDomain: 'learn-auth-ff6fe.firebaseapp.com',
    storageBucket: 'learn-auth-ff6fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZj8-yTjFsUlv1Xp7KtZOn-8lPofLIpKs',
    appId: '1:615484235727:android:c863aa7c6b4eba73b2bcba',
    messagingSenderId: '615484235727',
    projectId: 'learn-auth-ff6fe',
    storageBucket: 'learn-auth-ff6fe.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzV7FPkcV53i_I08YsA63Ghg6tf_ZLC8I',
    appId: '1:615484235727:ios:6c678b5f23ad6fa5b2bcba',
    messagingSenderId: '615484235727',
    projectId: 'learn-auth-ff6fe',
    storageBucket: 'learn-auth-ff6fe.appspot.com',
    androidClientId: '615484235727-hm5qha4d2q44if4sihpq8uttofhu7nv5.apps.googleusercontent.com',
    iosClientId: '615484235727-e0ta19bfo1b9cq0kh2td6cb2i9en8kvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASW-cm1sodJjoiHfmSEuWbMmmiu2D63hE',
    appId: '1:615484235727:web:dc1d1d4a14d922bdb2bcba',
    messagingSenderId: '615484235727',
    projectId: 'learn-auth-ff6fe',
    authDomain: 'learn-auth-ff6fe.firebaseapp.com',
    storageBucket: 'learn-auth-ff6fe.appspot.com',
  );

}